### PR TITLE
instructions-on-how-to-parallel_cucumber-test

### PR DESCRIPTION
**Pull request by sivvoy**

### CODE REVIEW

**Comment by Stivaros** [comment]
These steps didn't work for me and I'm on a different machine to yesterday, running full system from scratch. Are there any interim steps you run?

**Comment by sivvoy** [comment]
Did you managed to get this working now?

**Comment by Stivaros** [comment]
Still not working for me:
```terminal
./bin/dev/test_exec bundle exec parallel_cucumber features
8 processes for 21 features, ~ 2 features per process
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-38-36.806.flv (Errno::ENOENT)
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-32-33.564.flv (Errno::ENOENT)
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-35-39.286.flv (Errno::ENOENT)
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-18-24.871.flv (Errno::ENOENT)
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-33-24.595.flv (Errno::ENOENT)
No such file or directory @ apply2files - /app/tmp/capybara/video_2018-10-08-11-19-44.802.flv (Errno::ENOENT)
WARNING: The formatter ParallelTests::Gherkin::RuntimeLogger is using the deprecated formatter API which will be removed in v4.0 of Cucumber.

Using the parallel profile...
0 scenarios
0 steps
0m0.000s
WARNING: The formatter ParallelTests::Gherkin::RuntimeLogger is using the deprecated formatter API which will be removed in v4.0 of Cucumber.

Using the parallel profile...
0 scenarios
0 steps
0m0.000s

0 scenarios ()
0 steps ()

Took 1 seconds
cucumbers Failed
```

**Comment by Stivaros** [comment]
Closing this PR as the instruction was actually fine all along, it was the code that was wrong. It's now been fixed and the README in develop is accurate.

**Pull request closed without merging**
